Traceback (most recent call last):
  File "C:\Users\tomvanwoudenbe\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\tomvanwoudenbe\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\tomvanwoudenbe\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\tomvanwoudenbe\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\tomvanwoudenbe\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\tomvanwoudenbe\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\tomvanwoudenbe\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\tomvanwoudenbe\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%reset -f
import sympy as sp
w1 = sp.symbols('w1', cls=sp.Function)
C1, C2, C3, C4 = sp.symbols('C1 C2 C3 C4')
x = sp.symbols('x')

g = 10
R = sp.nsimplify(3.6/2)
t = sp.nsimplify(45/1000)
Area = sp.pi*R**2-sp.pi*(R-t)**2
Volume = Area*1
rho = 7850
p = rho*g*Area-1000*g*Volume
EI = sp.nsimplify(2e11*1/4*sp.pi*(R**4-(R-t)**4))

q = 1800
Ho = 12*1000000
L = 300

H1 = Ho
diffeq1 = sp.Eq(EI*sp.diff(w1(x),x,4)-H1*sp.diff(w1(x),x,2),q)
display(diffeq1)

bcs={w1(0): 0 ,
     w1(x).diff(x , 2).subs(x , 0) : 0 ,
     w1(x).diff(x , 2).subs(x , L) : 0 ,
     w1(x).diff(x , 3).subs(x , L) : 1/EI * H1 * w1(x).diff(x , 1).subs(x , L)}
w1 = sp.dsolve(diffeq1, w1(x),ics=bcs)
w1 = w1.rhs
display(w1)

sp.plotting.plot(w1,(x,0,L));


------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_22492\636833250.py[0m in [0;36m<module>[1;34m[0m
[0;32m     26[0m      [0mw1[0m[1;33m([0m[0mx[0m[1;33m)[0m[1;33m.[0m[0mdiff[0m[1;33m([0m[0mx[0m [1;33m,[0m [1;36m2[0m[1;33m)[0m[1;33m.[0m[0msubs[0m[1;33m([0m[0mx[0m [1;33m,[0m [0mL[0m[1;33m)[0m [1;33m:[0m [1;36m0[0m [1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m     27[0m      w1(x).diff(x , 3).subs(x , L) : 1/EI * H1 * w1(x).diff(x , 1).subs(x , L)}
[1;32m---> 28[1;33m [0mw1[0m [1;33m=[0m [0msp[0m[1;33m.[0m[0mdsolve[0m[1;33m([0m[0mdiffeq1[0m[1;33m,[0m [0mw1[0m[1;33m([0m[0mx[0m[1;33m)[0m[1;33m,[0m[0mics[0m[1;33m=[0m[0mbcs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     29[0m [0mw1[0m [1;33m=[0m [0mw1[0m[1;33m.[0m[0mrhs[0m[1;33m[0m[1;33m[0m[0m
[0;32m     30[0m [0mdisplay[0m[1;33m([0m[0mw1[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\sympy\solvers\ode\ode.py[0m in [0;36mdsolve[1;34m(eq, func, hint, simplify, ics, xi, eta, x0, n, **kwargs)[0m
[0;32m    603[0m [1;33m[0m[0m
[0;32m    604[0m         [1;31m# See the docstring of _desolve for more details.[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 605[1;33m         hints = _desolve(eq, func=func,
[0m[0;32m    606[0m             [0mhint[0m[1;33m=[0m[0mhint[0m[1;33m,[0m [0msimplify[0m[1;33m=[0m[1;32mTrue[0m[1;33m,[0m [0mxi[0m[1;33m=[0m[0mxi[0m[1;33m,[0m [0meta[0m[1;33m=[0m[0meta[0m[1;33m,[0m [0mtype[0m[1;33m=[0m[1;34m'ode'[0m[1;33m,[0m [0mics[0m[1;33m=[0m[0mics[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    607[0m             x0=x0, n=n, **kwargs)

[1;32m~\Anaconda3\lib\site-packages\sympy\solvers\deutils.py[0m in [0;36m_desolve[1;34m(eq, func, hint, ics, simplify, prep, **kwargs)[0m
[0;32m    207[0m     [1;31m# recursive calls.[0m[1;33m[0m[1;33m[0m[0m
[0;32m    208[0m     [1;32mif[0m [0mkwargs[0m[1;33m.[0m[0mget[0m[1;33m([0m[1;34m'classify'[0m[1;33m,[0m [1;32mTrue[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 209[1;33m         hints = classifier(eq, func, dict=True, ics=ics, xi=xi, eta=eta,
[0m[0;32m    210[0m         n=terms, x0=x0, hint=hint, prep=prep)
[0;32m    211[0m [1;33m[0m[0m

[1;32m~\Anaconda3\lib\site-packages\sympy\solvers\ode\ode.py[0m in [0;36mclassify_ode[1;34m(eq, func, dict, ics, prep, xi, eta, n, **kwargs)[0m
[0;32m   1002[0m                     [0mboundary[0m[1;33m.[0m[0mupdate[0m[1;33m([0m[1;33m{[0m[0mtemp[0m[1;33m:[0m [0mnew[0m[1;33m,[0m [0mtemp[0m [1;33m+[0m [1;34m'val'[0m[1;33m:[0m [0mics[0m[1;33m[[0m[0mfuncarg[0m[1;33m][0m[1;33m}[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1003[0m                 [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1004[1;33m                     [1;32mraise[0m [0mValueError[0m[1;33m([0m[1;34m"Enter valid boundary conditions for Derivatives"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1005[0m [1;33m[0m[0m
[0;32m   1006[0m [1;33m[0m[0m

[1;31mValueError[0m: Enter valid boundary conditions for Derivatives
ValueError: Enter valid boundary conditions for Derivatives

